# values for the addon
addons:
  ack_ec2:
    enabled: false
  ack_eks:
    enabled: false
  ack_iam:
    enabled: false
  ack_s3:
    enabled: false
  ack_secretsmanager:
    enabled: false
  adot_collector:
    enabled: true
  argocd:
    enabled: false # Disabled because is not deployed by the gitops-bridge helm chart and instead is deployed by the fleet-spoke-argocd ApplicationSet from the Hub Cluster https://github.com/aws-samples/fleet-management-on-amazon-eks-workshop/blob/riv24/gitops/fleet/bootstrap/control-plane/members-init/addons-argo-cd-appset.yaml
  aws_ebs_csi_resources:
    enabled: true
  aws_load_balancer_controller:
    enabled: true
  cert_manager:
    enabled: true
  cni_metrics_helper:
    enabled: true
  cw_prometheus:
    enabled: true
  eks_upgrade_insights_demo:
    enabled: true
  external_dns:
    enabled: false
  external_secrets:
    enabled: false # Disabled because is not deployed by the gitops-bridge helm chart and instead is deployed by the fleet-spoke-external-secrets ApplicationSet the Hub Cluster https://github.com/aws-samples/fleet-management-on-amazon-eks-workshop/blob/riv24/gitops/fleet/bootstrap/control-plane/members-init/addons-aws-oss-external-secrets-appset.yaml
  grafana_operator:
    enabled: true
  karpenter:
    enabled: true
  kube_state_metrics:
    enabled: true
  kro:
    enabled: false
  kyverno:
    enabled: true
  kyverno_policies:
    enabled: true
  kyverno_policy_reporter:
    enabled: true
  metrics_server:
    enabled: true
  opentelemetry_operator:
    enabled: true
  prometheus_node_exporter:
    enabled: true
